exp:
    weight_file: ""
    num_workers: 4
    batch_size: 32
    num_epochs: 200
    val_every: 10

model:
    encoder: "pointnet"
    pc_feat_dim: 256
    gnn_iter: 5
    noise_dim: 32

loss:
    trans_loss_w: 1.
    rot_pt_cd_loss_w: 10.
    transform_pt_cd_loss_w: 10.

data:
    data_dir: "../Generative-3D-Part-Assembly/prepare_data"
    data_fn: "Chair.{}.npy"

optimizer:
    lr: 1e-3
