exp:
    weight_file: ""
    num_workers: 8
    batch_size: 32
    num_epochs: 100
    val_every: 10

model:
    encoder: "pointnet"
    pc_feat_dim: 128
    gnn_iter: 5
    noise_dim: 0

loss:
    sample_iter: 1
    trans_loss_w: 1.
    rot_pt_cd_loss_w: 10.
    transform_pt_cd_loss_w: 10.

data:
    dataset: "geometry"
    data_dir: "/scratch/ssd004/scratch/ziyiwu/data/assembly"
    data_fn: "semantic_data.{}.csv"
    data_keys: ('part_ids', 'instance_label', 'valid_matrix')
    category: ""

optimizer:
    lr: 1e-3
