exp:
    weight_file: ""
    num_workers: 8
    batch_size: 32
    num_epochs: 200
    val_every: 10

model:
    encoder: "pointnet"
    pc_feat_dim: 256
    transformer_feat_dim: 1024
    transformer_heads: 8
    transformer_layers: 4
    noise_dim: 0

loss:
    sample_iter: 1
    trans_loss_w: 1.
    rot_pt_cd_loss_w: 10.
    transform_pt_cd_loss_w: 10.

data:
    dataset: "geometry"
    data_dir: "/scratch/ssd004/scratch/ziyiwu/data/assembly"
    data_fn: "semantic_data.{}.csv"
    data_keys: ('part_ids', 'instance_label')
    category: ""

optimizer:
    lr: 1e-3
    weight_decay: 0.
    warmup_ratio: 0.05
    clip_grad: null
