exp:
    name: "baseline"
    weight_file: ""
    num_workers: 4
    batch_size: 16
    num_epochs: 200
    val_every: 5

model:
    encoder: "pointnet"
    pc_feat_dim: 512
    transformer_feat_dim: 1024
    transformer_heads: 4
    transformer_layers: 1
    noise_dim: 32

loss:
    trans_loss_w: 1.
    rot_loss: ""
    rot_loss_w: 1.
    use_rot_pt_l2_loss: False
    rot_pt_l2_loss_w: 1.
    use_rot_pt_cd_loss: True
    rot_pt_cd_loss_w: 10.
    use_transform_pt_cd_loss: True
    transform_pt_cd_loss_w: 1.

data:
    data_dir: "../Generative-3D-Part-Assembly/prepare_data"
    data_fn: "Chair.{}.npy"
    data_keys: ('part_ids', 'instance_label', 'match_ids', 'contact_points')

optimizer:
    lr: 1e-3
    weight_decay: 0.
    warmup_ratio: 0.05
    clip_grad: null
