exp:
    weight_file: ""
    num_workers: 8
    batch_size: 32
    num_epochs: 200
    val_every: 10

model:
    encoder: "pointnet"
    pc_feat_dim: 128
    lstm_hidden_size: 256
    noise_dim: 0

loss:
    sample_iter: 1
    trans_loss_w: 1.
    rot_pt_cd_loss_w: 10.
    transform_pt_cd_loss_w: 10.
    rot_loss: ""
    rot_loss_w: 1.
    use_rot_pt_l2_loss: False
    rot_pt_l2_loss_w: 1.

data:
    dataset: "geometry"
    data_dir: "/scratch/ssd004/scratch/ziyiwu/data/assembly"
    data_fn: "semantic_data.{}.txt"
    data_keys: ('part_ids', 'instance_label')
    category: ""

optimizer:
    lr: 1e-3
